version: '2'

services:
  # Compute: HTTP API and task producer
  compute:
    build: ./compute-api
    restart: unless-stopped
    mem_limit: 50000000
    memswap_limit: 0
    command: -host 0.0.0.0 -port ${COMPUTE_PORT} -broker nsq -broker-host nsqd -broker-port 4150
    ports:
    - "${COMPUTE_PORT}:${COMPUTE_PORT}/tcp"
    networks:
    - internal
    depends_on:
    - nsqd

  # Compute: task consumer
  compute-worker:
    build: ./compute-worker
    restart: unless-stopped
    mem_limit: 50000000
    memswap_limit: 0
    environment:
    - "DOCKER_HOST=tcp://dind-executor:2376"
    command: -lookup-urls nsqlookupd:4161 -channel "compute"
    privileged: true
    networks:
    - internal
    depends_on:
    - nsqlookupd
    - dind-executor

  # Docker-in-Docker container to run untrusted code
  dind-executor:
    build: ./utils/dind-daemon
    mem_limit: 1000000000
    memswap_limit: 0
    restart: unless-stopped
    privileged: true
    networks:
    - internal

  # Nsqlookupd: service discovery for Nsqd
  nsqlookupd:
    image: nsqio/nsq:latest
    mem_limit: 50000000
    memswap_limit: 0
    restart: unless-stopped
    command: /nsqlookupd
    networks:
    - internal
    depends_on:
    - nsqd

  # Nsqd: the distributed broker
  nsqd:
    image: nsqio/nsq:latest
    mem_limit: 50000000
    memswap_limit: 0
    restart: unless-stopped
    command: /nsqd --lookupd-tcp-address="nsqlookupd:4160"
    networks:
    - internal

  # Nsq Admin frontend
  nsqadmin:
    image: nsqio/nsq:latest
    mem_limit: 50000000
    memswap_limit: 0
    restart: unless-stopped
    command: /nsqadmin --lookupd-http-address="nsqlookupd:4161"
    networks:
    - internal
    ports:
    - "4171:4171/tcp"

  # Storage
  storage:
    build: ./storage-api
    restart: unless-stopped
    command: -host 0.0.0.0 -port ${STORAGE_PORT}
    ## Stops the container from taking up all the cache memory on big file
    ## uploads
    mem_limit: 100000000
    memswap_limit: 100000000
    volumes:
    - ./data/storage:/data
    ports:
    - "${STORAGE_PORT}:${STORAGE_PORT}/tcp"
    networks:
    - internal
    depends_on:
    - postgres

  # Postgres instance for the storage service
  postgres:
    image: postgres:alpine
    mem_limit: 200000000
    memswap_limit: 0
    volumes:
    - ./data/postgres:/var/lib/postgres
    environment:
    - POSTGRES_PASSWORD=tooshort
    - POSTGRES_USER=storage
    - POSTGRES_DB=morpheo_storage
    networks:
      - internal

networks:
  # Accessible from the outside (a mock of what some call "the Internet")
  internal:
    driver: bridge
