version: '3'

services:
  # DC-Compute: producer
  compute:
    build: ./iris-api
    restart: unless-stopped
    command: -host 0.0.0.0 -port ${API_PORT} -broker nsq -broker-host nsqd -broker-port 4150
    ports:
    - "${API_PORT}:${API_PORT}/tcp"
    networks:
    - internal
    depends_on:
    - nsqd

  # DC-Compute: learning consumer
  compute-learning-consumer:
    build: ./consumer
    restart: unless-stopped
    environment:
    - "DOCKER_HOST=tcp://dind-executor:2376"
    command: -lookup-urls nsqlookupd:4161 -topic "train" -channel "compute"
    privileged: true
    networks:
    - internal
    depends_on:
    - nsqlookupd
    - dind-executor

  # Docker-in-Docker container to run untrusted code
  dind-executor:
    build: ./utils/dind-daemon
    restart: unless-stopped
    privileged: true
    networks:
    - internal

  # Nsqlookupd: service discovery for Nsqd
  nsqlookupd:
    image: nsqio/nsq:latest
    restart: unless-stopped
    command: /nsqlookupd
    networks:
    - internal
    depends_on:
    - nsqd

  # Nsqd: the distributed broker
  nsqd:
    image: nsqio/nsq:latest
    restart: unless-stopped
    command: /nsqd --lookupd-tcp-address="nsqlookupd:4160"
    networks:
    - internal

  # Nsq Admin frontend
  nsqadmin:
    image: nsqio/nsq:latest
    restart: unless-stopped
    command: /nsqadmin --lookupd-http-address="nsqlookupd:4161"
    networks:
    - internal
    ports:
    - "4171:4171/tcp"

networks:
  # Accessible from the outside (a mock of what some call "the Internet")
  internal:
    driver: bridge
