version: '3'

services:
  # DC-Compute: producer
  compute:
    build: ./iris-api
    command: -host 0.0.0.0 -port ${API_PORT} -broker nsq -broker-host nsqlookupd -broker-port 4160
    ports:
    - "${API_PORT}:${API_PORT}/tcp"
    networks:
    - internal

  # Nsqlookupd: service discovery for Nsqd
  nsqlookupd:
    image: nsqio/nsq:latest
    restart: unless-stopped
    command: /nsqlookupd
    networks:
    - internal

  # Nsqd: the distributed broker
  nsqd:
    image: nsqio/nsq:latest
    restart: unless-stopped
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    networks:
    - internal
#   ports:
#   - 4150
#   - 4151
  nsqadmin:
    image: nsqio/nsq:latest
    restart: unless-stopped
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    networks:
    - internal
    ports:
    - 4171

networks:
  # Accessible from the outside (a mock of what some call "the Internet")
  internal:
    driver: bridge
